training:
  epochs: 101
  workers: 4
  batch_size: 128
  weight_decay: 0.0
  mixed_precision: False 
  discriminator_lr: 2e-4
  generator_lr: 1e-3
  lambda_cat: 1.0
  lambda_cts: 0.1

model:
  num_noise: 62
  num_cts_codes: 2
  num_cat_codes: 1
  num_categories: 10

data:
  dataset: 'MNIST'

